In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 1101.P.2603_PUBLIC.xlsx to 1101.P.2603_PUBLIC (1).xlsx

In [ ]:
df=pd.read_excel('1101.P.2603_PUBLIC.xlsx')

## Explorar datos

In [ ]:
df.head(10)

,11 - 01 CONGRESO NACIONAL,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,AÑO,MES,NIVEL DE ESTRUC.,ENTIDAD,DEPENDENCIA,LINEA PRESUPUE,CÉDULA,NOMBRES,APELLIDOS,ESTADO,...,TIPO DE DESCAP.,AÑO DE INGRESO\n(*),OFICINA,PROFESION,CORREO ELECTRONICO,FECHA DE ACTO ADMINISTRATIVO,MOTIVO MOVIMIENTO,TIPIFICACION DEL CARGO DE,IDENTIFICADOR DE CONCURSO,(*)
1,2026,3,11,1,1,16000,249673,VICTOR JACINTO,FLECHA GONZALEZ,PERMANENTE,...,NaN,2019,1,LICENCIATURA EN ECONOMIA POLITICA,usuario1@senado.gov.py,2025-01-13 00:00:00,NaN,NO,NaN,NaN
2,2026,3,11,1,1,20000,263272,ADALBERTO RAMON,MONGELOS VALLOVERA,PERMANENTE,...,NaN,2005,1,BACHILLERATO,usuario1@senado.gov.py,2025-01-13 00:00:00,NaN,NO,NaN,NaN
3,2026,3,11,1,1,60000,286144,JULIO DANIEL,PEREIRA ACOSTA,PERMANENTE,...,NaN,2011,1,ELECTRICISTA,usuario1@senado.gov.py,2011-11-01 00:00:00,NaN,NO,NaN,NaN
4,2026,3,11,1,1,50000,298946,JUSTO PASTOR,RIVAS MARTINEZ,PERMANENTE,...,NaN,2016,1,PRIMARIA,usuario1@senado.gov.py,2016-01-01 00:00:00,NaN,NO,NaN,NaN
5,2026,3,11,1,1,20000,334317,MARIA DEL CARMEN,BAEZ JOU,PERMANENTE,...,NaN,2011,1,LICENCIADO EN RELACIONES INTERNACIONALES,usuario1@senado.gov.py,2012-09-01 00:00:00,NaN,NO,NaN,NaN
6,2026,3,11,1,1,0,334317,MARIA DEL CARMEN,BAEZ JOU,PERMANENTE,...,NaN,2011,1,LICENCIADO EN RELACIONES INTERNACIONALES,usuario1@senado.gov.py,2012-09-01 00:00:00,NaN,NO,NaN,NaN
7,2026,3,11,1,1,32000,349953,OSCAR ALFONZO,GARCIA DUARTE,PERMANENTE,...,NaN,2010,1,BACHILLERATO,usuario1@senado.gov.py,2024-06-26 00:00:00,NaN,NO,NaN,NaN
8,2026,3,11,1,1,8000,352659,MARIA CRISTINA VERONICA,ASHWELL FERNANDEZ,PERMANENTE,...,NaN,2016,1,LICENCIATURA LENGUA INGLESA,usuario1@senado.gov.py,2011-01-01 00:00:00,NaN,NO,NaN,NaN
9,2026,3,11,1,1,53000,361523,GUMERSINDA GRACIELA,MARIN PEREIRA,PERMANENTE,...,NaN,2012,1,BACHILLERATO,usuario1@senado.gov.py,2012-05-02 00:00:00,NaN,NO,NaN,NaN

Al observar, vemos que la primera fila molesta y no nos permite tener las columnas verdaderas como columnas.
Por ello, usaremos el siguiente código, que le indica cuál columna usaremos como encabezado:
df.columns = df.iloc[0]
El número cero refiere a la primera fila de nuestro dataset

In [ ]:
df.columns = df.iloc[0]

Ahora vemos cómo quedó:

In [ ]:
df.head(5)

,AÑO,MES,NIVEL DE ESTRUC.,ENTIDAD,DEPENDENCIA,LINEA PRESUPUE,CÉDULA,NOMBRES,APELLIDOS,ESTADO,...,TIPO DE DESCAP.,AÑO DE INGRESO\n(*),OFICINA,PROFESION,CORREO ELECTRONICO,FECHA DE ACTO ADMINISTRATIVO,MOTIVO MOVIMIENTO,TIPIFICACION DEL CARGO DE,IDENTIFICADOR DE CONCURSO,(*)
0,AÑO,MES,NIVEL DE ESTRUC.,ENTIDAD,DEPENDENCIA,LINEA PRESUPUE,CÉDULA,NOMBRES,APELLIDOS,ESTADO,...,TIPO DE DESCAP.,AÑO DE INGRESO\n(*),OFICINA,PROFESION,CORREO ELECTRONICO,FECHA DE ACTO ADMINISTRATIVO,MOTIVO MOVIMIENTO,TIPIFICACION DEL CARGO DE,IDENTIFICADOR DE CONCURSO,(*)
1,2026,3,11,1,1,16000,249673,VICTOR JACINTO,FLECHA GONZALEZ,PERMANENTE,...,NaN,2019,1,LICENCIATURA EN ECONOMIA POLITICA,usuario1@senado.gov.py,2025-01-13 00:00:00,NaN,NO,NaN,NaN
2,2026,3,11,1,1,20000,263272,ADALBERTO RAMON,MONGELOS VALLOVERA,PERMANENTE,...,NaN,2005,1,BACHILLERATO,usuario1@senado.gov.py,2025-01-13 00:00:00,NaN,NO,NaN,NaN
3,2026,3,11,1,1,60000,286144,JULIO DANIEL,PEREIRA ACOSTA,PERMANENTE,...,NaN,2011,1,ELECTRICISTA,usuario1@senado.gov.py,2011-11-01 00:00:00,NaN,NO,NaN,NaN
4,2026,3,11,1,1,50000,298946,JUSTO PASTOR,RIVAS MARTINEZ,PERMANENTE,...,NaN,2016,1,PRIMARIA,usuario1@senado.gov.py,2016-01-01 00:00:00,NaN,NO,NaN,NaN

Ahora vamos a borrar la fila una, que en realidad era nuestro encabezado. Así usaremos el siguiente código. df = df.iloc[1:]
Esto crea nuevamente el dataset, pero selecciona todas las filas desde la segunda fila. Recordemos que se usa el número 1, porque la primera fila es "0" en Python.

In [ ]:
df = df.iloc[1:]

Vemos como quedó con df.head()

In [ ]:
df.head(5)

,AÑO,MES,NIVEL DE ESTRUC.,ENTIDAD,DEPENDENCIA,LINEA PRESUPUE,CÉDULA,NOMBRES,APELLIDOS,ESTADO,...,TIPO DE DESCAP.,AÑO DE INGRESO\n(*),OFICINA,PROFESION,CORREO ELECTRONICO,FECHA DE ACTO ADMINISTRATIVO,MOTIVO MOVIMIENTO,TIPIFICACION DEL CARGO DE,IDENTIFICADOR DE CONCURSO,(*)
1,2026,3,11,1,1,16000,249673,VICTOR JACINTO,FLECHA GONZALEZ,PERMANENTE,...,NaN,2019,1,LICENCIATURA EN ECONOMIA POLITICA,usuario1@senado.gov.py,2025-01-13 00:00:00,NaN,NO,NaN,NaN
2,2026,3,11,1,1,20000,263272,ADALBERTO RAMON,MONGELOS VALLOVERA,PERMANENTE,...,NaN,2005,1,BACHILLERATO,usuario1@senado.gov.py,2025-01-13 00:00:00,NaN,NO,NaN,NaN
3,2026,3,11,1,1,60000,286144,JULIO DANIEL,PEREIRA ACOSTA,PERMANENTE,...,NaN,2011,1,ELECTRICISTA,usuario1@senado.gov.py,2011-11-01 00:00:00,NaN,NO,NaN,NaN
4,2026,3,11,1,1,50000,298946,JUSTO PASTOR,RIVAS MARTINEZ,PERMANENTE,...,NaN,2016,1,PRIMARIA,usuario1@senado.gov.py,2016-01-01 00:00:00,NaN,NO,NaN,NaN
5,2026,3,11,1,1,20000,334317,MARIA DEL CARMEN,BAEZ JOU,PERMANENTE,...,NaN,2011,1,LICENCIADO EN RELACIONES INTERNACIONALES,usuario1@senado.gov.py,2012-09-01 00:00:00,NaN,NO,NaN,NaN

Utilice df.tail(10) para mirar las últimas diez filas de los datos:

In [ ]:
df.tail(5)

,AÑO,MES,NIVEL DE ESTRUC.,ENTIDAD,DEPENDENCIA,LINEA PRESUPUE,CÉDULA,NOMBRES,APELLIDOS,ESTADO,...,TIPO DE DESCAP.,AÑO DE INGRESO\n(*),OFICINA,PROFESION,CORREO ELECTRONICO,FECHA DE ACTO ADMINISTRATIVO,MOTIVO MOVIMIENTO,TIPIFICACION DEL CARGO DE,IDENTIFICADOR DE CONCURSO,(*)
1659,2026,3,11,1,1,0,6547353,MONICA LORENA,TRINIDAD RUIZ DIAZ,CONTRATADO,...,NaN,2023,1,LICENCIATURA EN CIENCIAS DE LA COMUNICACION,lore.jaur@gmail.com,2025-04-01 00:00:00,NaN,NO,NaN,NaN
1660,2026,3,11,1,1,0,6547353,MONICA LORENA,TRINIDAD RUIZ DIAZ,CONTRATADO,...,NaN,2023,1,LICENCIATURA EN CIENCIAS DE LA COMUNICACION,lore.jaur@gmail.com,2025-04-01 00:00:00,NaN,NO,NaN,NaN
1661,2026,3,11,1,1,0,8585860,YESICA MARIA,RUIZ DIAZ VILLALBA,CONTRATADO,...,NaN,2024,1,ABOGADO,yesiruizdiaz@gmail.com,2024-07-01 00:00:00,NaN,NO,NaN,NaN
1662,2026,3,11,1,1,0,8585860,YESICA MARIA,RUIZ DIAZ VILLALBA,CONTRATADO,...,NaN,2024,1,ABOGADO,yesiruizdiaz@gmail.com,2024-07-01 00:00:00,NaN,NO,NaN,NaN
1663,* AÑO DE INGRESO : INCLUYE PRIMER VINCULO...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Para ver una muestra aleatoria del conjunto de datos, escriba `df.sample(5)`.

In [ ]:
df.sample(5)

,AÑO,MES,NIVEL DE ESTRUC.,ENTIDAD,DEPENDENCIA,LINEA PRESUPUE,CÉDULA,NOMBRES,APELLIDOS,ESTADO,...,TIPO DE DESCAP.,AÑO DE INGRESO\n(*),OFICINA,PROFESION,CORREO ELECTRONICO,FECHA DE ACTO ADMINISTRATIVO,MOTIVO MOVIMIENTO,TIPIFICACION DEL CARGO DE,IDENTIFICADOR DE CONCURSO,(*)
642,2026,3,11,1,1,30000,2959360,JORGE RICARDO,GARCIA CESPEDES,PERMANENTE,...,NaN,2011,1,BACHILLERATO,usuario1@senado.gov.py,2025-01-13 00:00:00,NaN,NO,NaN,NaN
1458,2026,3,11,1,1,0,4352377,NESTOR FABRIZIO,CANO OLMEDO,CONTRATADO,...,NaN,2023,1,LICENCIATURA EN CIENCIAS CONTABLES,usuario1@senado.gov.py,2024-07-01 00:00:00,NaN,NO,NaN,NaN
813,2026,3,11,1,1,0,3613503,JORGE JOSE HUMBERTO,GOMEZ CHAMORRO,PERMANENTE,...,NaN,2011,1,BACHILLERATO,humberg-18@holmail.com,2011-10-01 00:00:00,NaN,NO,NaN,NaN
738,2026,3,11,1,1,0,3419874,CLAUDIA CAROLINA,MERELES,PERMANENTE,...,NaN,2010,1,ABOGADO,usuario1@senado.gov.py,2010-12-01 00:00:00,NaN,NO,NaN,NaN
1495,2026,3,11,1,1,0,5085511,KARINA ELIZABETH,SULING MARECO,CONTRATADO,...,NaN,2023,1,BACHILLERATO,usuario1@senado.gov.py,2026-02-02 00:00:00,NaN,NO,NaN,NaN

A continuación, queremos saber qué tipos de datos manejamos para cada columna de nuestro dataframe.

In [ ]:
df.dtypes

0
AÑO                             object
MES                             object
NIVEL DE ESTRUC.                object
ENTIDAD                         object
DEPENDENCIA                     object
LINEA PRESUPUE                  object
CÉDULA                          object
NOMBRES                         object
APELLIDOS                       object
ESTADO                          object
REMUNERACION TOTAL              object
OBJETO DEL                      object
FUNTE DE FINANCIAM.             object
CAT.                            object
PRESUPUESTADO                   object
DEVENGADO                       object
CONCEPTO                        object
CODIGO DE MOV.                  object
LUGAR DE COMISIONAMIENTO        object
CARGO                           object
FUNCION                         object
CARGA HORARIA                   object
DISCAP.                         object
TIPO DE DESCAP.                 object
AÑO DE INGRESO\n(*)             object
OFICINA                         object
PROFESION                       object
CORREO ELECTRONICO              object
FECHA DE ACTO ADMINISTRATIVO    object
MOTIVO MOVIMIENTO               object
TIPIFICACION DEL CARGO DE       object
IDENTIFICADOR DE CONCURSO       object
(*)                             object
dtype: object

Ahora necesito convertir las columnas de números a int y de texto a string, para que Python los reconozca para cálculos.
Comencemos con las que deben pasar a texto.

Definimos en una variable las columnas:
columnas_texto = ['Nombre', 'Ciudad']

Ahora utilizamos la función de cambiar a tipo:
df[columnas_texto] = df[columnas_texto].astype('string')

In [ ]:
columnas_texto = ['NOMBRES', 'APELLIDOS','CARGO','FUNCION','OFICINA','PROFESION']
df[columnas_texto] = df[columnas_texto].astype('string')

In [ ]:
#Veamos la conversión:
df.dtypes

0
AÑO                                     object
MES                                     object
NIVEL DE ESTRUC.                        object
ENTIDAD                                 object
DEPENDENCIA                             object
LINEA PRESUPUE                          object
CÉDULA                                  object
NOMBRES                         string[python]
APELLIDOS                       string[python]
ESTADO                                  object
REMUNERACION TOTAL                      object
OBJETO DEL                              object
FUNTE DE FINANCIAM.                     object
CAT.                                    object
PRESUPUESTADO                           object
DEVENGADO                               object
CONCEPTO                                object
CODIGO DE MOV.                          object
LUGAR DE COMISIONAMIENTO                object
CARGO                           string[python]
FUNCION                         string[python]
CARGA HORARIA                           object
DISCAP.                                 object
TIPO DE DESCAP.                         object
AÑO DE INGRESO\n(*)                     object
OFICINA                         string[python]
PROFESION                       string[python]
CORREO ELECTRONICO                      object
FECHA DE ACTO ADMINISTRATIVO            object
MOTIVO MOVIMIENTO                       object
TIPIFICACION DEL CARGO DE               object
IDENTIFICADOR DE CONCURSO               object
(*)                                     object
dtype: object

Ahora pasaremos a números las columnas que queramos. En el caso de la columna "REMUNERACION TOTAL", es importante, limpiar antes los datos.
1- Pasar a texto la columna, para poder usar las funciones de texto.
2- Eliminar los espacios en blanco al inicio y al final.
3- Eliminar comas
4- Reemplazar posibles valores vacíos con NaN.

Finalmente, podemos convertir la columna a una columna numérica.

In [ ]:
# Limpiar la columna 'REMUNERACION TOTAL' antes de convertir a numérico

# Convertir a string para asegurar que podemos usar métodos de string
df['REMUNERACION TOTAL'] = df['REMUNERACION TOTAL'].astype(str)

# Eliminar espacios en blanco al inicio y final
df['REMUNERACION TOTAL'] = df['REMUNERACION TOTAL'].str.strip()

# Eliminar las comas (si las hay)
df['REMUNERACION TOTAL'] = df['REMUNERACION TOTAL'].str.replace(',', '', regex=False)

# Reemplazar posibles valores vacíos o no numéricos restantes con NaN antes de la conversión
df['REMUNERACION TOTAL'] = df['REMUNERACION TOTAL'].replace('', pd.NA)


# Convertir la columna 'REMUNERACION TOTAL' a numérica.
# Usamos errors='coerce' para convertir cualquier valor que aún no sea numérico a NaN
df['REMUNERACION TOTAL'] = pd.to_numeric(df['REMUNERACION TOTAL'], errors='coerce')

Ahora cambiamos las demás columnas que nos interesan a números. Por ejemplo "DEVENGADO", repitiendo el procedimiento.

In [ ]:
# Limpiar la columna 'DEVENGADO' antes de convertir a numérico

# Convertir a string para asegurar que podemos usar métodos de string
df['DEVENGADO'] = df['DEVENGADO'].astype(str)

# Eliminar espacios en blanco al inicio y final
df['DEVENGADO'] = df['DEVENGADO'].str.strip()

# Eliminar las comas (si las hay)
df['DEVENGADO'] = df['DEVENGADO'].str.replace(',', '', regex=False)

# Reemplazar posibles valores vacíos o no numéricos restantes con NaN antes de la conversión
df['DEVENGADO'] = df['DEVENGADO'].replace('', pd.NA)


# Convertir la columna 'DEVENGADO' a numérica.
# Usamos errors='coerce' para convertir cualquier valor que aún no sea numérico a NaN
df['DEVENGADO'] = pd.to_numeric(df['DEVENGADO'], errors='coerce')

In [ ]:
df.dtypes

0
AÑO                                     object
MES                                     object
NIVEL DE ESTRUC.                        object
ENTIDAD                                 object
DEPENDENCIA                             object
LINEA PRESUPUE                          object
CÉDULA                                  object
NOMBRES                         string[python]
APELLIDOS                       string[python]
ESTADO                                  object
REMUNERACION TOTAL                     float64
OBJETO DEL                              object
FUNTE DE FINANCIAM.                     object
CAT.                                    object
PRESUPUESTADO                           object
DEVENGADO                              float64
CONCEPTO                                object
CODIGO DE MOV.                          object
LUGAR DE COMISIONAMIENTO                object
CARGO                           string[python]
FUNCION                         string[python]
CARGA HORARIA                           object
DISCAP.                                 object
TIPO DE DESCAP.                         object
AÑO DE INGRESO\n(*)                     object
OFICINA                         string[python]
PROFESION                       string[python]
CORREO ELECTRONICO                      object
FECHA DE ACTO ADMINISTRATIVO            object
MOTIVO MOVIMIENTO                       object
TIPIFICACION DEL CARGO DE               object
IDENTIFICADOR DE CONCURSO               object
(*)                                     object
dtype: object

Para ver la forma del marco de datos (el número de filas y columnas), escriba `df.shape`.

In [ ]:
df.shape

(1663, 33)

Para ver un resumen estadístico descriptivo de nuestros datos, incluido el valor medio y la mediana de cada columna, escriba `df.describe()`

In [ ]:
# Configurar pandas para no usar notación científica para floats y mostrar hasta 2 decimales
pd.options.display.float_format = '{:,.2f}'.format

df.describe()

# Opcional: Restablecer la configuración a la predeterminada si lo deseas
# pd.reset_option('display.float_format')

0      REMUNERACION TOTAL     DEVENGADO
count            1,011.00      1,662.00
mean         9,628,989.96  5,791,732.16
std          6,053,406.34  3,947,796.92
min            400,000.00          0.00
25%          5,500,000.00  2,850,000.00
50%          8,047,305.00  5,000,000.00
75%         12,000,000.00  8,000,000.00
max         39,185,789.00 20,000,000.00

count: El número de valores no nulos.
mean: La media o promedio.
std: La desviación estándar, que mide la dispersión de los datos.
min: El valor mínimo.
25%: El primer cuartil (percentil 25).
50%: La mediana (percentil 50).
75%: El tercer cuartil (percentil 75).
max: El valor máximo.

## Limpiar fechas

Bien, ahora solo nos queda limpiar las fechas.

In [ ]:
# Convertir la columna 'FECHA DE ACTO ADMINISTRATIVO' a datetime
# Usamos errors='coerce' para convertir valores no válidos a NaT (Not a Time)
df['FECHA DE ACTO ADMINISTRATIVO'] = pd.to_datetime(df['FECHA DE ACTO ADMINISTRATIVO'], errors='coerce')

Ahora bien, ¿cambió el tipo de dato de la columna AcceptedDate? Use `df.dtypes` para comprobarlo.

In [ ]:
df.dtypes

0
AÑO                                     object
MES                                     object
NIVEL DE ESTRUC.                        object
ENTIDAD                                 object
DEPENDENCIA                             object
LINEA PRESUPUE                          object
CÉDULA                                  object
NOMBRES                         string[python]
APELLIDOS                       string[python]
ESTADO                                  object
REMUNERACION TOTAL                     float64
OBJETO DEL                              object
FUNTE DE FINANCIAM.                     object
CAT.                                    object
PRESUPUESTADO                           object
DEVENGADO                              float64
CONCEPTO                                object
CODIGO DE MOV.                          object
LUGAR DE COMISIONAMIENTO                object
CARGO                           string[python]
FUNCION                         string[python]
CARGA HORARIA                           object
DISCAP.                                 object
TIPO DE DESCAP.                         object
AÑO DE INGRESO\n(*)                     object
OFICINA                         string[python]
PROFESION                       string[python]
CORREO ELECTRONICO                      object
FECHA DE ACTO ADMINISTRATIVO    datetime64[ns]
MOTIVO MOVIMIENTO                       object
TIPIFICACION DEL CARGO DE               object
IDENTIFICADOR DE CONCURSO               object
(*)                                     object
dtype: object

Si queremos crear nuevas columnas a partir de datos que tenemos, podemos hacerlo. Por ejemplo, creamos una nueva columna con el año que se muestra en la columna "FECHA DE ACTO ADMINISTRATIVO"

In [ ]:
df['AÑO2']= pd.DatetimeIndex(df['FECHA DE ACTO ADMINISTRATIVO']).year
#Aquí creamos la columna, y luego le decimos a python de dónde sacar los datos

In [ ]:
df.columns

Index(['AÑO', 'MES', 'NIVEL DE ESTRUC.', 'ENTIDAD', 'DEPENDENCIA',
       'LINEA PRESUPUE', 'CÉDULA', 'NOMBRES', 'APELLIDOS', 'ESTADO',
       'REMUNERACION TOTAL', 'OBJETO DEL', 'FUNTE DE FINANCIAM.', 'CAT.',
       'PRESUPUESTADO', 'DEVENGADO', 'CONCEPTO', 'CODIGO DE MOV.',
       'LUGAR DE COMISIONAMIENTO', 'CARGO', 'FUNCION', 'CARGA HORARIA',
       'DISCAP.', 'TIPO DE DESCAP.', 'AÑO DE INGRESO\n(*)', 'OFICINA',
       'PROFESION', 'CORREO ELECTRONICO', 'FECHA DE ACTO ADMINISTRATIVO',
       'MOTIVO MOVIMIENTO', 'TIPIFICACION DEL CARGO DE',
       'IDENTIFICADOR DE CONCURSO', '(*)', 'AÑO2'],
      dtype='object', name=0)

# Eliminar columnas

Nuestro marco de datos es bastante grande. ¿Podríamos eliminar algunas columnas? Veamos cuántas tenemos... Usa `df.columns` y `df.shape` para familiarizarte con el número de columnas y sus nombres.

In [ ]:
df.columns

Index(['AÑO', 'MES', 'NIVEL DE ESTRUC.', 'ENTIDAD', 'DEPENDENCIA',
       'LINEA PRESUPUE', 'CÉDULA', 'NOMBRES', 'APELLIDOS', 'ESTADO',
       'REMUNERACION TOTAL', 'OBJETO DEL', 'FUNTE DE FINANCIAM.', 'CAT.',
       'PRESUPUESTADO', 'DEVENGADO', 'CONCEPTO', 'CODIGO DE MOV.',
       'LUGAR DE COMISIONAMIENTO', 'CARGO', 'FUNCION', 'CARGA HORARIA',
       'DISCAP.', 'TIPO DE DESCAP.', 'AÑO DE INGRESO\n(*)', 'OFICINA',
       'PROFESION', 'CORREO ELECTRONICO', 'FECHA DE ACTO ADMINISTRATIVO',
       'MOTIVO MOVIMIENTO', 'TIPIFICACION DEL CARGO DE',
       'IDENTIFICADOR DE CONCURSO', '(*)', 'AÑO2'],
      dtype='object', name=0)

In [ ]:
df.shape

(1663, 34)

¡Eliminemos algunas columnas!

df = df.drop('Value', axis=1) #eliminar varias columnas
df = df.drop(['Value', 'Fecha', 'Monto'], axis=1) #si querés eliminar varias columnas:



O quizás deberíamos decirle al ordenador qué columnas queremos conservar. Podría ser más corto. :)
Usa `dfMini = df[['DEPENDENCIA', 'CÉDULA', 'NOMBRES', 'APELLIDOS',
       'REMUNERACION TOTAL', 'OBJETO DEL GASTO','CONCEPTO', 'CARGO', 'FUNCION', 'CARGA HORARIA', 'AÑO DE INGRESO\n(*)', 'OFICINA',
       'PROFESION', 'TIPIFICACION DEL CARGO DE CONFIANZA', 'AÑO2']]`

In [ ]:
dfMini = df[['DEPENDENCIA', 'CÉDULA', 'NOMBRES', 'APELLIDOS','REMUNERACION TOTAL','DEVENGADO','CONCEPTO', 'CARGO', 'FUNCION', 'CARGA HORARIA', 'AÑO DE INGRESO\n(*)', 'OFICINA','PROFESION', 'TIPIFICACION DEL CARGO DE']]

In [ ]:
dfMini.sample(5)

,DEPENDENCIA,CÉDULA,NOMBRES,APELLIDOS,REMUNERACION TOTAL,DEVENGADO,CONCEPTO,CARGO,FUNCION,CARGA HORARIA,AÑO DE INGRESO\n(*),OFICINA,PROFESION,TIPIFICACION DEL CARGO DE
599,1,2615152,MAGIN RAMON,DUETTE ESTECHE,NaN,"6,000,000.00",BONIFICACION POR RESPONSABILIDAD,<NA>,COMISION BICAMERAL DE PRESUPUESTO-DIRECTOR GEN...,HORARIO-MOVIL,1999,1,ABOGADO,NO
447,1,2200933,KARINA OFELIA,TORRES CATTEBEKE,NaN,"2,700,000.00",BONIFICACION POR RESPONSABILIDAD,<NA>,ASISTENTE,07:00 A 13:00,2011,1,SIN DATOS,NO
307,1,1742137,RODRIGO DANIEL,ESCALADA BURIAN,NaN,"223,004.00",PASAJES Y VIATICOS,<NA>,DIRECCION GENERAL DE DIARIO DE SESIONES-JEFE D...,07:00 A 13:00,2010,1,BACHILLERATO,NO
614,1,2859428,JESICA DEL ROSARIO,ZAYAS VEGA,NaN,"758,329.00",REMUNERACION EXTRAORDINARIA - CORRESPONDIENTE ...,<NA>,GERENCIA GENERAL DEL CAPITAL HUMANO-COORDINACI...,07:00 A 13:00,2018,1,PROFESOR DE CIENCIAS SOCIALES,NO
453,1,2209866,FANY CLAUDELINA,REBOLLO VERGARA,"20,837,700.00","13,500,000.00",SUELDO,PROFESIONAL II,CCRC-COORDINACION DE LOGISTICA INSTITUCIONAL-C...,07:00 A 13:00,2023,1,ABOGADO,NO

## Guardar tus datos

Ahora que hemos dedicado todo este trabajo a limpiar nuestro conjunto de datos, guardemos una copia.

Para bajar el archivo desde Gooogle Colab a la computadora

In [ ]:


# Guardar los datos limpios en un CSV file
dfMini.to_csv('Senado_limpio 4.csv')

# Descargar el CSV file
files.download('Senado_limpio 4.csv')

Ahora podemos analizar otros aspectos de lo encontrado. Por ejemplo, ¿cuántas bonificaciones se entregan? ¿Cuánto se gasta en salarios?

In [ ]:
df["DEVENGADO"].describe()
#Te muestra mínimo, máximo, media, mediana, desviación estándar, etc.
#Si el máximo es extremadamente alto, podrías investigar si hay
#sobrefacturación o carga errónea.

count        1,662.00
mean     5,791,732.16
std      3,947,796.92
min              0.00
25%      2,850,000.00
50%      5,000,000.00
75%      8,000,000.00
max     20,000,000.00
Name: DEVENGADO, dtype: float64

In [ ]:
dfconceptos["DEVENGADO"].sum() #El gasto total devengado

np.float64(9625858845.0)

In [ ]:
dfconceptos.groupby("CONCEPTO")["DEVENGADO"].sum().reset_index()
#El gasto según concepto

                                             CONCEPTO        DEVENGADO
0                   - CORRESPONDIENTE AL MES DE ENERO     4,453,565.00
1   BONIFICACION POR GESTION ADMINISTRATIVA Y MANE...    88,069,142.00
2   BONIFICACION POR GESTION ADMINISTRATIVA Y MANE...     1,650,000.00
3   BONIFICACION POR GESTION ADMINISTRATIVA Y MANE...    13,260,000.00
4                    BONIFICACION POR RESPONSABILIDAD 1,157,742,643.00
5   BONIFICACION POR RESPONSABILIDAD - CORRESPONDI...     8,070,000.00
6   BONIFICACION POR RESPONSABILIDAD - CORRESPONDI...    10,552,643.00
7       ESCALAFON - CORRESPONDIENTE AL MES DE FEBRERO    10,884,790.00
8        ESCALAFON DEL PERSONAL DEL PODER LEGISLATIVO   297,119,230.00
9            GRATIFICACIONES POR SERVICIOS ESPECIALES   108,800,000.00
10  GRATIFICACIONES POR SERVICIOS ESPECIALES - COR...    20,000,000.00
11                                 PASAJES Y VIATICOS   107,174,320.00
12  REMUNERACION EXTRAORDINARIA - CORRESPONDIENTE ...    23,911,635.00
13  REMUNERACION EXTRAORDINARIA - CORRESPONDIENTE ...    39,189,917.00
14                                  SUBSIDIO FAMILIAR   142,800,000.00
15                                             SUELDO 7,434,083,816.00
16         SUELDO - CORRESPONDIENTE AL MES DE FEBRERO   158,097,144.00

In [ ]:
dfconceptos.groupby("CONCEPTO")["DEVENGADO"].mean().reset_index()
#El promedio de lo que se gastó en cada concepto

                                             CONCEPTO    DEVENGADO
0                   - CORRESPONDIENTE AL MES DE ENERO   890,713.00
1   BONIFICACION POR GESTION ADMINISTRATIVA Y MANE... 1,467,819.03
2   BONIFICACION POR GESTION ADMINISTRATIVA Y MANE... 1,650,000.00
3   BONIFICACION POR GESTION ADMINISTRATIVA Y MANE... 1,657,500.00
4                    BONIFICACION POR RESPONSABILIDAD 3,163,231.27
5   BONIFICACION POR RESPONSABILIDAD - CORRESPONDI... 2,690,000.00
6   BONIFICACION POR RESPONSABILIDAD - CORRESPONDI... 2,110,528.60
7       ESCALAFON - CORRESPONDIENTE AL MES DE FEBRERO 2,721,197.50
8        ESCALAFON DEL PERSONAL DEL PODER LEGISLATIVO 3,909,463.55
9            GRATIFICACIONES POR SERVICIOS ESPECIALES 2,014,814.81
10  GRATIFICACIONES POR SERVICIOS ESPECIALES - COR... 2,000,000.00
11                                 PASAJES Y VIATICOS 6,698,395.00
12  REMUNERACION EXTRAORDINARIA - CORRESPONDIENTE ...   996,318.12
13  REMUNERACION EXTRAORDINARIA - CORRESPONDIENTE ... 1,152,644.62
14                                  SUBSIDIO FAMILIAR 4,080,000.00
15                                             SUELDO 8,002,243.07
16         SUELDO - CORRESPONDIENTE AL MES DE FEBRERO 4,940,535.75

In [ ]:
dfconceptos["CONCEPTO"].value_counts()
#¿Cuántas veces se pagó en nombre de cada concepto?

CONCEPTO
SUELDO                                                                         929
BONIFICACION POR RESPONSABILIDAD                                               366
ESCALAFON DEL PERSONAL DEL PODER LEGISLATIVO                                    76
BONIFICACION POR GESTION ADMINISTRATIVA Y MANEJO DE SISTEMA                     60
GRATIFICACIONES POR SERVICIOS ESPECIALES                                        54
SUBSIDIO FAMILIAR                                                               35
REMUNERACION EXTRAORDINARIA - CORRESPONDIENTE AL MES DE FEBRERO                 34
SUELDO - CORRESPONDIENTE AL MES DE FEBRERO                                      32
REMUNERACION EXTRAORDINARIA - CORRESPONDIENTE AL MES DE ENERO                   24
PASAJES Y VIATICOS                                                              16
GRATIFICACIONES POR SERVICIOS ESPECIALES - CORRESPONDIENTE AL MES D             10
BONIFICACION POR GESTION ADMINISTRATIVA Y MANEJO DE SISTEMA - CORRESPONDIEN      8
BONIFICACION POR RESPONSABILIDAD - CORRESPONDIENTE AL MES DE FEBRE               5
- CORRESPONDIENTE AL MES DE ENERO                                                5
ESCALAFON - CORRESPONDIENTE AL MES DE FEBRERO                                    4
BONIFICACION POR RESPONSABILIDAD - CORRESPONDIENTE AL MES DE ENER                3
BONIFICACION POR GESTION ADMINISTRATIVA Y MANEJO DE SISTEMA - CORR               1
Name: count, dtype: int64

Ahora podemos analizar la relación de los salarios en torno a funciones y cargos que poseen el dato de dependencia.

In [ ]:
dfcargos= dfMini[["CARGO","FUNCION","DEVENGADO", "REMUNERACION TOTAL"]].copy()
dfcargos.head()

,CARGO,FUNCION,DEVENGADO,REMUNERACION TOTAL
1,PROFESIONAL III,CENTRO CULTURAL DE LA REPUBLICA EL CABILDO-ASI...,"10,000,000.00","10,000,000.00"
2,TECNICO III,CENTRO CULTURAL DE LA REPUBLICA EL CABILDO-DIR...,"9,000,000.00","9,000,000.00"
3,TECNICO V,DIRECCION GENERAL DE TALENTO HUMANO-DIRECCION ...,"5,000,000.00","5,000,000.00"
4,TECNICO IV,DIRECCION GENERAL DE SEGURIDAD Y CONTROL-AUXILIAR,"6,500,000.00","6,500,000.00"
5,TECNICO IV,BIBLIOTECA DEL CN-JEFE DE SECCION DE DISTRIBUCION,"6,000,000.00","7,800,000.00"

In [ ]:
dfcargos.groupby("CARGO")["DEVENGADO"].sum().reset_index().sort_values("DEVENGADO", ascending=False)
#El gasto según cargo

                         CARGO        DEVENGADO
15             PROFESIONAL III 1,835,500,000.00
20                  TECNICO IV 1,125,000,000.00
19                 TECNICO III   869,000,000.00
4              ESPECIALISTA II   775,800,000.00
10                    JORNALES   533,860,102.00
9     HONORARIOS PROFESIONALES   503,500,000.00
11         PERSONAL DE APOYO I   407,800,000.00
14              PROFESIONAL II   321,200,000.00
18                  TECNICO II   304,000,000.00
21                   TECNICO V   197,500,000.00
3               ESPECIALISTA I   179,700,000.00
13               PROFESIONAL I   132,900,000.00
16            PROFESIONAL III3   110,500,000.00
5             ESPECIALISTA III    84,400,000.00
17                   TECNICO I    70,000,000.00
7               ESPECIALISTA V    57,500,000.00
6              ESPECIALISTA IV    50,500,000.00
0     ASIST. TECN. ADMINIST. I    48,000,000.00
12               PROFESIOAN II    28,000,000.00
22                   TENICO IV    26,000,000.00
1   ASIST. TECNIC. ADMINIST. I    13,000,000.00
2            ASISTENTE TECNICO    12,000,000.00
8             ESPECIALISTA VII     9,500,000.00

In [ ]:
dfcargos.groupby("CARGO")["REMUNERACION TOTAL"].mean().reset_index().sort_values("REMUNERACION TOTAL", ascending=False)
#El promedio de lo que se gastó según cargos

                         CARGO  REMUNERACION TOTAL
3               ESPECIALISTA I       31,465,303.22
4              ESPECIALISTA II       25,037,991.74
12               PROFESIOAN II       21,374,114.50
13               PROFESIONAL I       20,715,962.50
5             ESPECIALISTA III       20,231,430.00
6              ESPECIALISTA IV       20,039,922.50
14              PROFESIONAL II       19,642,958.64
7               ESPECIALISTA V       17,767,430.00
17                   TECNICO I       16,490,000.00
8             ESPECIALISTA VII       15,637,700.00
18                  TECNICO II       14,380,538.04
1   ASIST. TECNIC. ADMINIST. I       11,159,730.00
19                 TECNICO III       11,150,121.20
15             PROFESIONAL III       10,677,057.50
16            PROFESIONAL III3        9,284,615.38
0     ASIST. TECN. ADMINIST. I        8,363,418.00
20                  TECNICO IV        7,980,084.58
22                   TENICO IV        7,962,500.00
9     HONORARIOS PROFESIONALES        7,828,694.48
2            ASISTENTE TECNICO        6,000,000.00
21                   TECNICO V        5,747,903.05
10                    JORNALES        5,170,096.21
11         PERSONAL DE APOYO I        5,106,000.72

In [ ]:
dfcargos["CARGO"].value_counts()
#¿Cuántas personas hay en cada cargo?

CARGO
PROFESIONAL III               209
TECNICO IV                    167
JORNALES                      154
HONORARIOS PROFESIONALES      113
TECNICO III                    95
PERSONAL DE APOYO I            87
ESPECIALISTA II                46
TECNICO V                      41
TECNICO II                     27
PROFESIONAL II                 22
PROFESIONAL III3               13
ESPECIALISTA I                  9
ASIST. TECN. ADMINIST. I        8
PROFESIONAL I                   8
ESPECIALISTA III                6
ESPECIALISTA V                  5
TECNICO I                       5
TENICO IV                       4
ESPECIALISTA IV                 4
ASISTENTE TECNICO               2
PROFESIOAN II                   2
ASIST. TECNIC. ADMINIST. I      2
ESPECIALISTA VII                1
Name: count, dtype: Int64